name: Terraform Destroy

on:
  workflow_dispatch: # Цей тригер дозволяє запускати конвеєр вручну з інтерфейсу GitHub

jobs:
  destroy:
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: ./task1

    env:
      # Використовуємо ті ж секрети, що і для deploy
      AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
      AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}

    steps:
      - name: Checkout Code
        uses: actions/checkout@v4

      - name: Setup Terraform
        uses: hashicorp/setup-terraform@v3

      - name: Terraform Init
        run: terraform init

      - name: Terraform Destroy
        # Команда знищення ресурсів без запиту на підтвердження
        run: terraform destroy -auto-approve